name: Deploy

on:
  push:
    branches: [production]
  workflow_dispatch:
    branches: [production]

concurrency: production

jobs:
  ci:
    name: CI
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/ci.yml
    secrets:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
  build:
    name: Build
    permissions:
      contents: read
      id-token: write
      packages: write
    needs: ci
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - uses: google-github-actions/auth@v0
        id: gcloud-auth
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Authenticate to Google Container Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.gcloud-auth.outputs.access_token }}
      - name: Authenticate to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate short SHA
        id: vars
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      - name: Build and push container images
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            gcr.io/${{ env.GCP_PROJECT }}/${{ github.repository }}:${{ steps.vars.outputs.short_sha }}
            gcr.io/${{ env.GCP_PROJECT }}/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.short_sha }}
            ghcr.io/${{ github.repository }}:latest
          target: production
  deploy:
    name: Deploy
    permissions:
      contents: read
      id-token: write
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://spaceholder.cc
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      - uses: google-github-actions/deploy-cloudrun@v0
        with:
          image: gcr.io/${{ env.GCP_PROJECT }}/${{ github.repository }}
          service: spaceholder-cc-web
